services:
  target-api:
    build: ./target-api
    container_name: target-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  monitor:
    build: ./monitor
    container_name: monitor
    environment:
      - TARGET_URL=http://target-api:8000/health
      - CONTAINER_NAME=target-api
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - PROMETHEUS_URL=http://prometheus:9090
      - TZ=America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./baseline.csv:/app/baseline.csv:ro
    depends_on:
      - target-api
      - prometheus
    restart: always

  dashboard:
    image: nginx:alpine
    container_name: dashboard
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
      - ./dashboard/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - target-api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
