services:
  target-api:
    build: ./target-api
    container_name: target-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  monitor:
    build: ./monitor
    container_name: monitor
    environment:
      - TARGET_URL=http://target-api:8000/health
      - CONTAINER_NAME=target-api
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    depends_on:
      - target-api
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
